### ISSUE TITLE
Service volumes at the barrel flange are not symmetric on z

### ISSUE THREAD

**Issue by alkemyst** [tkLayout/tkLayout#18]
Is a minor problem, but it could lead to some unexpected clash of volumes if only the positive side is checked (see pictures, where the picture of services at z<0 was
![service_positive](https://cloud.githubusercontent.com/assets/584822/7273378/64a86bd8-e8f3-11e4-9a82-1eb3408dda60.png)
![service_negative_flip](https://cloud.githubusercontent.com/assets/584822/7273377/64a67d5a-e8f3-11e4-91a0-638c9fcfa369.png)

 flipped to ease the comparison)

**Comment by ghugo83** [comment]
Hey! I made a PR for this bug.

**Comment by alkemyst** [comment]
Solved by @ghugo83
