### ISSUE TITLE
Module count in the pixel endcap

### ISSUE THREAD

**Issue by alkemyst** [tkLayout/tkLayout#22]
In the main geometry summary page the number of modules in the end-cap is wrong.

**Comment by ghugo83** [comment]
After careful check I don't find any bug in the count of pixel modules for the 'layers and disks' tab and the 'modules' tab of the geometry summary page with respect to what is expected in tkLayout.

**Comment by alkemyst** [comment]
Then I am going to close this issue. In case this bug surfaces again in some geometry we can always open it again.
