### ISSUE TITLE
XML extractor should behave correctly with "empty" service volume

### ISSUE THREAD

**Issue by alkemyst** [tkLayout/tkLayout#26]
We should make sure that the xml producer would not have problems when creating inactive volumes, in case there is an InactiveSurface containing no materials.

**Comment by ryonamin** [comment]
Can you provide a specific config file to reproduce the error you got? I thought it should not be any problem but maybe I missed something.

**Comment by alkemyst** [comment]
Hi, Ryo.
Can I consider this issue closed?

**Comment by ryonamin** [comment]
Hi Stefano, yes this was already solved!
