### ISSUE TITLE
Duplicate composite material definietions

### ISSUE THREAD

**Issue by alkemyst** [tkLayout/tkLayout#49]
The same composite material defined multiple times with different names.
This is partly legacy from old code, where the service materials were embedded in the module volumes, so each combination of ring/layer would have a different material amount.
Still now we might have different material content for each ring, so in order to remove this we would need a dedicated mechanism to prune duplicate material definitions. It is a desirable improvement, albeit not an urgent one.

**Comment by ghugo83** [comment]
Dear Stefano,
Do you mean the duplication of composite material definitions in the XMLs ? This was solved when working on reducing the size of the XMLs.
Or in the core of tkLayout ?
Cheers

**Comment by alkemyst** [comment]
This was on the XML export. If I understood correctly you can close this issue :-)
