### ISSUE TITLE
Rotation of barrel during export

### ISSUE THREAD

**Issue by alkemyst** [tkLayout/tkLayout#86]
Dueing the export from tkLayout to CMSSW (CMSSW_6_2_0_SLHC25_patch) and undesired 90-degree rotation appears (see puctires)
![cmssw](https://cloud.githubusercontent.com/assets/584822/10277454/3de59d46-6b56-11e5-814f-17d107a26270.png)
![img001](https://cloud.githubusercontent.com/assets/584822/10277455/3de5acf0-6b56-11e5-93ab-71815fe6c919.png)

**Comment by ghugo83** [comment]
The mismatch is for CMSSW_6_2_0_SLHC25_patch branch, which is using old xmls (where there is barrel start angle = 0, endcaps start angle = pi).
For the CMSSW_6_2_SLHCDEV_X branch (and soon CMSSW_7_6_X), there is no mismatch. (We have barrel start angle = 90 degrees and endcaps start angle = 0 for both tkLayout + simulations with Fireworks)
